### ISSUE TITLE
scale up/down policy

### ISSUE THREAD

**Issue by maweina** [TeraprocSoftware/jaguar#1]
1. Commit Slider resize container
2. Enhance Jaguar scale up/down policy
3. End-to-end scale-up/down test

**Comment by maweina** [comment]
(Done) Flex-up instance.
(Done) Flex-down instance.

Example flex-up policy:

{
  "name": "flexUpHBase",
  "description": "flex up HBase region server",
  "enabled": false,
  "interval": 60,
  "timezone": "UTC",
  "cron": "? \* MON-FRI",
  "startTime": "9:00:00",
  "duration": "10H00M00S",
  "alert": {
    "successiveIntervals": 2,
    "condition": {
        "componentName": "HBASE_REGIONSERVER",
        "expression": "last(ProcessCallTime_mean)>=100"
    }
  },
  "actions": [
    {
      "componentName": "HBASE_REGIONSERVER",
      "cooldown": 60,
      "adjustmentType": "DELTA_COUNT",
      "scalingAdjustment": {
        "CPU": {
          "min": 1,
          "max": 2,
          "adjustment": 1
        },
        "MEMORY": {
          "min": 1014,
          "max": 2048,
          "adjustment": 1024
        }
      }
    }
  ]
}

**Comment by ading1977** [comment]
[https://github.com/TeraprocSoftware/jaguar/commit/70d6f16708a4e9812dbf07061f53a3d9e2ce961b](https://github.com/TeraprocSoftware/jaguar/commit/70d6f16708a4e9812dbf07061f53a3d9e2ce961b)
