### ISSUE TITLE
Provide proper distribution package

### ISSUE THREAD

**Issue by ading1977** [TeraprocSoftware/jaguar#10]
We need a standard directory layout for distribution package. 

After `gradlew clean build`, and untar the `build/distributions/jaguar-<version>.tar`, the following directory layout is expected:

```
bin
conf
docs
lib
```

**Comment by ading1977** [comment]
Commit the initial patch

**Comment by maweina** [comment]
Added log configuration file to package: $TOP/conf/logback.xml [39790a1 ](https://github.com/TeraprocSoftware/jaguar/commit/39790a1becfac5ca421417fc8007413f875a5f72)

Requirements for package:
i) Jaguar conf "jaguar-env.sh" should include  $JAGUAR_HOME.
ii) Jaguar should be started like "java -jar ./lib/jaguar-0.4.DEV.jar --logging.config=$JAGUAR_HOME/conf/logback.xml"

**Comment by maweina** [comment]
[Design document of adding jaguar as Ambari custom service](https://docs.google.com/document/d/1YnipJw8P5NJcqk3Rw_91yovmn1T3fORv0zCaK6Ak8ig/edit?usp=sharing)

**Comment by maweina** [comment]
1. Display rpm package information

[root@jaguar2 resources]# rpm -qip ./jaguar-0.4.DEV-1.noarch.rpm
Name        : jaguar                       Relocations: (not relocatable)
Version     : 0.4.DEV                           Vendor: Teraproc
Release     : 1                             Build Date: Tue 01 Mar 2016 08:06:26 PM UTC
Install Date: (not installed)               Build Host: UOFL14-PK2HT3G
Group       : (none)   Source RPM: jaguar-0.4.DEV-1-src.rpm
Size        : 93515625                         License: GPL
Signature   : (none)
Packager    : 100513145
URL         : http://www.teraproc.com/
Summary     : Jaguar server and client programs
Description :
Autoscalling engine for slider-managed long running services in yarn cluster
1. Install rpm

[root@jaguar2 resources]# rpm -ivh ./jaguar-0.4.DEV-1.noarch.rpm
Preparing...                ########################################### [100%]
   1:jaguar                 ########################################### [100%]
1. By default jaguar is installed to /opt

[root@jaguar2 resources]# ll /opt/jaguar-0.4.DEV/
total 20
drwxr-xr-x 3 root root 4096 Mar  1 20:12 bin
drwxr-xr-x 2 root root 4096 Mar  1 20:12 conf
drwxr-xr-x 2 root root 4096 Mar  1 20:12 docs
drwxr-xr-x 2 root root 4096 Mar  1 20:13 lib
drwxr-xr-x 2 root root 4096 Mar  1 18:23 logs

**Comment by maweina** [comment]
1. Add directory sbin/ to ${JAGUAR_HOME} 
   [root@jaguar2 jaguar-0.4.DEV]# ll /opt/jaguar-0.4.DEV/
   total 28
   drwxr-xr-x 3 root root  4096 Mar  7 18:35 bin
   drwxr-xr-x 2 root root  4096 Mar  7 18:35 conf
   drwxr-xr-x 2 root root  4096 Mar  7 18:35 docs
   drwxr-xr-x 2 root root 12288 Mar  7 18:35 lib
   drwxr-xr-x 2 root root  4096 Mar  7 18:35 sbin

[root@jaguar2 conf]# tree /opt/jaguar-0.4.DEV/sbin/
/opt/jaguar-0.4.DEV/sbin/
└── jaguar-daemon.sh

"logs/" and "events/" are generated at runtime.
1. After installing jaguar rpm, configure jaguar as follows:
   1) set environment "export JAGUAR_CONF_DIR=/opt/jaguar-0.4.DEV/conf"
   2) modify following configuration files
   [root@jaguar2 jaguar-0.4.DEV]# tree conf/
   conf/
   ├── jaguar.conf.template
   ├── jaguar-env.sh.template
   ├── jaguar.properties.template
   └── logback.xml
2. Start jaguar by running "/opt/jaguar-0.4.DEV/sbin/jaguar-daemon.sh start"

**Comment by maweina** [comment]
Attach design doc: Add Jaguar Service to Ambari
[package.docx](https://github.com/TeraprocSoftware/jaguar/files/192007/package.docx)
