### ISSUE TITLE
Jaguar policy REST API issues

### ISSUE THREAD

**Issue by ading1977** [TeraprocSoftware/jaguar#15]
When working on Jaguar CLI, I discovered the following Jaguar policy API issues:
- Jaguar cannot list all policies (both group and instance) that belong to an application:

```
vagrant@mdinglin02:~/workspace/jaguar$ jaguar policy list 50
404
{
  "error": "Not Found",
  "message": "",
  "status": 404,
  "timestamp": 1456251047505
}
```
- Jaguar cannot list all instance policies that belong to an application:

```
vagrant@mdinglin02:~/workspace/jaguar$ jaguar policy list 50 --type instance
500
{
  "message": null
}
```
- Jaguar does not return error when listing policies of group type, but specifying instance policy IDs. For example, the following command specify policy type of 'group', but 201 is an ID of instance policy. The command still returns:

```
vagrant@mdinglin02:~/workspace/jaguar$ jaguar policy list 50 --type group --id 201
200
{
  "actions": [
    {
      "adjustmentType": "DELTA_COUNT",
      "componentName": "HBASE_REGIONSERVER",
      "cooldown": 60,
      "scalingAdjustment": {
        "CPU": {
          "adjustment": 1,
          "max": 2,
          "min": 1
        },
        "MEMORY": {
          "adjustment": 1024,
          "max": 2048,
          "min": 1014
        }
      }
    }
  ],
  "alert": {
    "condition": {
      "componentName": "HBASE_REGIONSERVER",
      "expression": "last(ProcessCallTime_mean)>=0"
    },
    "successiveIntervals": 3
  },
  "applicationId": 50,
  "cron": "? * MON-FRI",
  "description": "flex up HBase region server",
  "duration": "10H00M00S",
  "enabled": false,
  "id": 201,
  "interval": 20,
  "name": "flexUpHBase",
  "startTime": "9:00:00",
  "timezone": "UTC"
}
```

**Comment by maweina** [comment]
Above fix supports:

1) Querying all policies of an application
 jaguar --server localhost:8080 policy list 1250 | jq '.[] | .id'
1650
1300
1302

2) Query instance polices of an application
jaguar --server localhost:8080 policy list 1250 --type instance | jq '.[] | .id'
1300

3) Query group polices of an application
jaguar --server localhost:8080 policy list 1250 --type group |jq '.[] | .id'
1650
1302

**Comment by maweina** [comment]
Above fix supports:

4) Return 404 not found error when listing policies of group type, but specifying instance policy IDs.

jaguar --server localhost:8080 policy list 1250 --type group  --id 1650 | jq '. | .id'
1650

 jaguar --server localhost:8080 policy list 1250 --type instance  --id 1650
404
{
  "message": "Policy not found"
}
