### ISSUE TITLE
Jaguar CLI

### ISSUE THREAD

**Issue by maweina** [TeraprocSoftware/jaguar#5]

**Comment by ading1977** [comment]
The initial commit [98fb22c](https://github.com/TeraprocSoftware/jaguar/commit/98fb22cc9bb3baa300e22eccce51c77d7a4265e2) address the client side CLI. 

The CLI should also support starting of the Jaguar service, which will be implemented later.

**Comment by maweina** [comment]
Need update following code in "src/main/resources/bin/jaguar-daemon.sh" after implementing to start jaguar service.

_# exec "${JAGUAR_HOME}/bin/jaguar" "$@"

# temp start command

java -classpath  ".:${JAGUAR_HOME}/lib/*" com.teraproc.jaguar.JaguarApplication --spring.config.location=${JAGUAR_CONF_DIR}/jaguar.properties --logging.config=${JAGUAR_CONF_DIR}/logback.xml > /dev/null 2>&1 &_

**Comment by ading1977** [comment]
Start/stop/status CLI is added:

Add Jaguar CLI for service start/stop/status
Support start as daemon or non-daemon mode
Remove jaguar-daemon.sh
Update logback configuration to toggle between FILE and STDOUT depending on daemon/non-daemon mode
