### ISSUE TITLE
Documentation in Chinese

### ISSUE THREAD

**Issue by maweina** [TeraprocSoftware/jaguar#7]
1. Installation
2. Admin

**Comment by maweina** [comment]
Initial draft.
[Jaguar 文档中文版.docx](https://github.com/TeraprocSoftware/jaguar/files/174929/Jaguar.docx)

**Comment by maweina** [comment]
Updater after first-round review. 
[Jaguar 文档中文版 v2.docx](https://github.com/TeraprocSoftware/jaguar/files/178713/Jaguar.v2.docx)

**Comment by maweina** [comment]
[Jaguar 文档中文版 v3.docx](https://github.com/TeraprocSoftware/jaguar/files/194514/Jaguar.v3.docx)

**Comment by ading1977** [comment]
Update a CLI typo
[Jaguar.v3.docx](https://github.com/TeraprocSoftware/jaguar/files/195912/Jaguar.v3.docx)
